language: python
arch:
    - amd64
    - ppc64le
addons:
  apt:
    packages:
    - g++
    - python-dev
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
python:
  - "3.3"
  - "3.4"
sudo: false
install:
  - "source ./install_dependencies.sh"
script: "python setup.py test"
